# Generated by Django 5.2.17 on 2026-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="rooms/")),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("living_room", "Living Room"),
                            ("bedroom", "Bedroom"),
                            ("kitchen", "Kitchen"),
                            ("dining_room", "Dining Room"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("analysis", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
