# Generated by Django 5.2.17 on 2026-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="annotated_image",
            field=models.ImageField(blank=True, null=True, upload_to="annotated/"),
        ),
        migrations.AddField(
            model_name="room",
            name="decorated_image",
            field=models.ImageField(blank=True, null=True, upload_to="decorated/"),
        ),
        migrations.AddField(
            model_name="room",
            name="depth_map",
            field=models.ImageField(blank=True, null=True, upload_to="depth/"),
        ),
        migrations.AddField(
            model_name="room",
            name="point_cloud",
            field=models.FileField(blank=True, null=True, upload_to="3d/"),
        ),
        migrations.AddField(
            model_name="room",
            name="suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="Room", max_length=200),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("living_room", "Living Room"),
                    ("bedroom", "Bedroom"),
                    ("kitchen", "Kitchen"),
                    ("dining_room", "Dining Room"),
                    ("office", "Office"),
                    ("gym", "Home Gym"),
                    ("reading_nook", "Reading Nook"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
