FURNITURE = {
    "living_room": [
        {
            "name": "2_seater_sofa",
            "file": "models/furniture/living_room/double_sofas.png",
            "width": 1.7,
            "depth": 0.85,
            "clearance": 0.6,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "3_seater_sofa",
            "file": "models/furniture/living_room/double_sofas.png",
            "width": 2.1,
            "depth": 0.9,
            "clearance": 0.6,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "coffee_table",
            "file": "models/furniture/living_room/table.png",
            "width": 1.2,
            "depth": 0.6,
            "clearance": 0.5,
            "category": "table",
            "is_wall_item": False,
        },
        {
            "name": "gaming_tv_unit",
            "file": "models/furniture/entertainment/gaming_tv_unit.png",
            "width": 1.5,
            "depth": 0.5,
            "clearance": 0.6,
            "category": "entertainment",
            "is_wall_item": False,
        },
        {
            "name": "indoor_plant",
            "file": "models/furniture/decor/indoor_plant.png",
            "width": 0.6,
            "depth": 0.6,
            "clearance": 0.2,
            "category": "decor",
            "is_wall_item": False,
        },
        {
            "name": "wall_art",
            "file": "models/furniture/decor/wall_art.png",
            "width": 1.0,
            "depth": 0.05,
            "clearance": 0.0,
            "category": "wall_decor",
            "is_wall_item": True,
        },
    ],

    "bedroom": [
        {
            "name": "single_bed",
            "file": "models/furniture/bedroom/singlebed.png",
            "width": 1.0,
            "depth": 2.0,
            "clearance": 0.6,
            "category": "bed",
            "is_wall_item": False,
        },
        {
            "name": "double_bed",
            "file": "models/furniture/bedroom/doublebed.png",
            "width": 1.6,
            "depth": 2.0,
            "clearance": 0.6,
            "category": "bed",
            "is_wall_item": False,
        },
        {
            "name": "wardrobe",
            "file": "models/furniture/bedroom/almari.png",
            "width": 1.2,
            "depth": 0.6,
            "clearance": 0.6,
            "category": "storage",
            "is_wall_item": False,
        },
        {
            "name": "study_desk",
            "file": "models/furniture/office/desk.png",
            "width": 1.3,
            "depth": 0.65,
            "clearance": 0.7,
            "category": "study",
            "is_wall_item": False,
        },
        {
            "name": "study_chair",
            "file": "models/furniture/office/officechair.png",
            "width": 0.65,
            "depth": 0.65,
            "clearance": 0.5,
            "category": "study",
            "is_wall_item": False,
        },
        {
            "name": "gaming_tv_unit",
            "file": "models/furniture/entertainment/gaming_tv_unit.png",
            "width": 1.4,
            "depth": 0.5,
            "clearance": 0.6,
            "category": "entertainment",
            "is_wall_item": False,
        },
        {
            "name": "lounge_couch",
            "file": "models/furniture/living_room/single_sofa.png",
            "width": 1.4,
            "depth": 0.8,
            "clearance": 0.5,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "wall_art",
            "file": "models/furniture/decor/wall_art.png",
            "width": 0.9,
            "depth": 0.05,
            "clearance": 0.0,
            "category": "wall_decor",
            "is_wall_item": True,
        },
        {
            "name": "wall_shelf",
            "file": "models/furniture/decor/wall_shelf.png",
            "width": 1.1,
            "depth": 0.25,
            "clearance": 0.0,
            "category": "wall_decor",
            "is_wall_item": True,
        },
    ],

    "office": [
        {
            "name": "office_desk",
            "file": "models/furniture/office/desk.png",
            "width": 1.5,
            "depth": 0.75,
            "clearance": 0.8,
            "category": "desk",
            "is_wall_item": False,
        },
        {
            "name": "office_chair",
            "file": "models/furniture/office/officechair.png",
            "width": 0.7,
            "depth": 0.7,
            "clearance": 0.6,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "bookshelf",
            "file": "models/furniture/office/bookrack.png",
            "width": 0.9,
            "depth": 0.35,
            "clearance": 0.5,
            "category": "storage",
            "is_wall_item": False,
        },
        {
            "name": "visitor_chair",
            "file": "models/furniture/living_room/single_sofa.png",
            "width": 1.3,
            "depth": 0.8,
            "clearance": 0.5,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "indoor_plant",
            "file": "models/furniture/decor/indoor_plant.png",
            "width": 0.6,
            "depth": 0.6,
            "clearance": 0.2,
            "category": "decor",
            "is_wall_item": False,
        },
        {
            "name": "wall_art",
            "file": "models/furniture/decor/wall_art.png",
            "width": 1.0,
            "depth": 0.05,
            "clearance": 0.0,
            "category": "wall_decor",
            "is_wall_item": True,
        },
    ],

    "gym": [
        {
            "name": "dumbbells_rack",
            "file": "models/furniture/gym/dumbbells_rack.png",
            "width": 1.4,
            "depth": 0.7,
            "clearance": 0.8,
            "category": "fitness",
            "is_wall_item": False,
        },
        {
            "name": "fitness_mirror",
            "file": "models/furniture/gym/fitness_mirror.png",
            "width": 0.8,
            "depth": 0.1,
            "clearance": 0.5,
            "category": "fitness_mirror",
            "is_wall_item": False,
        },
        {
            "name": "pull_up_bar",
            "file": "models/furniture/gym/pull_up_bar.png",
            "width": 1.2,
            "depth": 0.5,
            "clearance": 0.0,
            "category": "fitness_wall",
            "is_wall_item": True,
        },
    ],

    "reading_nook": [
        {
            "name": "bookshelf",
            "file": "models/furniture/office/bookrack.png",
            "width": 0.85,
            "depth": 0.35,
            "clearance": 0.5,
            "category": "bookshelf",
            "is_wall_item": False,
        },
        {
            "name": "reading_chair",
            "file": "models/furniture/living_room/single_sofa.png",
            "width": 1.2,
            "depth": 0.8,
            "clearance": 0.5,
            "category": "seating",
            "is_wall_item": False,
        },
        {
            "name": "wall_shelf",
            "file": "models/furniture/decor/wall_shelf.png",
            "width": 1.0,
            "depth": 0.25,
            "clearance": 0.0,
            "category": "wall_decor",
            "is_wall_item": True,
        },
        {
            "name": "indoor_plant",
            "file": "models/furniture/decor/indoor_plant.png",
            "width": 0.55,
            "depth": 0.55,
            "clearance": 0.2,
            "category": "decor",
            "is_wall_item": False,
        },
    ],

    "dining_room": [
        {
            "name": "dining_table",
            "file": "models/furniture/dining_room/diningtable.png",
            "width": 1.6,
            "depth": 0.9,
            "clearance": 0.9,
            "category": "table",
            "is_wall_item": False,
        },
        {
            "name": "dining_chair",
            "file": "models/furniture/dining_room/chair.png",
            "width": 0.5,
            "depth": 0.5,
            "clearance": 0.6,
            "category": "seating",
            "is_wall_item": False,
        },
    ],
}